spring:
  datasource:
    url: jdbc:mysql://rooforall.mysql.database.azure.com/rooforall?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: rooforall@rooforall
    password: Mif@root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
